# Pulls the mysql image and installs the database
FROM mysql:8.0

# Copies the db_structure.sql into db_scripts (overwrites the sql script if found the same script)
COPY ../DB_Scripts/database_structure.sql /db_scripts/

